var searchData=
[
  ['back_5finsert_5fiterator',['back_insert_iterator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00617.html',1,'std']]],
  ['bad_5falloc',['bad_alloc',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00618.html',1,'std']]],
  ['bad_5fcast',['bad_cast',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00619.html',1,'std']]],
  ['bad_5fexception',['bad_exception',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00620.html',1,'std']]],
  ['bad_5ffunction_5fcall',['bad_function_call',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00621.html',1,'std']]],
  ['bad_5ftypeid',['bad_typeid',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00622.html',1,'std']]],
  ['bad_5fweak_5fptr',['bad_weak_ptr',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00623.html',1,'std']]],
  ['balanced_5fquicksort_5ftag',['balanced_quicksort_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00168.html',1,'__gnu_parallel']]],
  ['balanced_5ftag',['balanced_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00169.html',1,'__gnu_parallel']]],
  ['bases',['bases',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00933.html',1,'std::tr2']]],
  ['basic_5fbranch',['basic_branch',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00187.html',1,'__gnu_pbds']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20cmp_5ffn_2c_20detail_3a_3atree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; Cmp_Fn, detail::tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00187.html',1,'__gnu_pbds']]],
  ['basic_5fbranch_3c_20key_2c_20mapped_2c_20tag_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_3a_3anode_5fupdate_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20_5fatraits_2c_20detail_3a_3atrie_5ftraits_3c_20key_2c_20mapped_2c_20_5fatraits_2c_20node_5fupdate_2c_20tag_2c_20_5falloc_20_3e_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_branch&lt; Key, Mapped, Tag, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt;::node_update, __gnu_cxx::typelist::create2&lt; _ATraits, detail::trie_traits&lt; Key, Mapped, _ATraits, Node_Update, Tag, _Alloc &gt; &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00187.html',1,'__gnu_pbds']]],
  ['basic_5fbranch_5ftag',['basic_branch_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00188.html',1,'__gnu_pbds']]],
  ['basic_5ffilebuf',['basic_filebuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00448.html',1,'std']]],
  ['basic_5ffstream',['basic_fstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00624.html',1,'std']]],
  ['basic_5fhash_5ftable',['basic_hash_table',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00189.html',1,'__gnu_pbds']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20cc_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate1_3c_20comb_5fhash_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, cc_hash_tag, __gnu_cxx::typelist::create1&lt; Comb_Hash_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00189.html',1,'__gnu_pbds']]],
  ['basic_5fhash_5ftable_3c_20key_2c_20mapped_2c_20hash_5ffn_2c_20eq_5ffn_2c_20resize_5fpolicy_2c_20store_5fhash_2c_20gp_5fhash_5ftag_2c_20_5f_5fgnu_5fcxx_3a_3atypelist_3a_3acreate2_3c_20comb_5fprobe_5ffn_2c_20probe_5ffn_20_3e_3a_3atype_2c_20_5falloc_20_3e',['basic_hash_table&lt; Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, gp_hash_tag, __gnu_cxx::typelist::create2&lt; Comb_Probe_Fn, Probe_Fn &gt;::type, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00189.html',1,'__gnu_pbds']]],
  ['basic_5fhash_5ftag',['basic_hash_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00190.html',1,'__gnu_pbds']]],
  ['basic_5fifstream',['basic_ifstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00625.html',1,'std']]],
  ['basic_5finvalidation_5fguarantee',['basic_invalidation_guarantee',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00191.html',1,'__gnu_pbds']]],
  ['basic_5fios',['basic_ios',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00449.html',1,'std']]],
  ['basic_5fiostream',['basic_iostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00450.html',1,'std']]],
  ['basic_5fistream',['basic_istream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00451.html',1,'std']]],
  ['basic_5fistringstream',['basic_istringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00627.html',1,'std']]],
  ['basic_5fofstream',['basic_ofstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00628.html',1,'std']]],
  ['basic_5fostream',['basic_ostream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00452.html',1,'std']]],
  ['basic_5fostringstream',['basic_ostringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00630.html',1,'std']]],
  ['basic_5fregex',['basic_regex',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00631.html',1,'std']]],
  ['basic_5fstreambuf',['basic_streambuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00453.html',1,'std']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00454.html',1,'std']]],
  ['basic_5fstring',['basic_string',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00093.html',1,'__gnu_debug']]],
  ['basic_5fstringbuf',['basic_stringbuf',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00632.html',1,'std']]],
  ['basic_5fstringstream',['basic_stringstream',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00633.html',1,'std']]],
  ['bernoulli_5fdistribution',['bernoulli_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00634.html',1,'std']]],
  ['bidirectional_5fiterator_5ftag',['bidirectional_iterator_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00636.html',1,'std']]],
  ['bin_5fsearch_5ftree_5fconst_5fit_5f',['bin_search_tree_const_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00213.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fconst_5fnode_5fit_5f',['bin_search_tree_const_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00214.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fit_5f',['bin_search_tree_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00215.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5fnode_5fit_5f',['bin_search_tree_node_it_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00216.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits',['bin_search_tree_traits',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00217.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00217.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20mapped_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20mapped_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, Mapped, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, Mapped, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, Mapped, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00217.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20node_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, Node, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00218.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20rb_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, rb_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00217.html',1,'__gnu_pbds::detail']]],
  ['bin_5fsearch_5ftree_5ftraits_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20splay_5ftree_5fnode_5f_3c_20types_5ftraits_3c_20key_2c_20null_5ftype_2c_20_5falloc_2c_20false_20_3e_3a_3avalue_5ftype_2c_20tree_5fnode_5fmetadata_5fdispatch_3c_20key_2c_20null_5ftype_2c_20cmp_5ffn_2c_20node_5fupdate_2c_20_5falloc_20_3e_3a_3atype_2c_20_5falloc_20_3e_2c_20_5falloc_20_3e',['bin_search_tree_traits&lt; Key, null_type, Cmp_Fn, Node_Update, splay_tree_node_&lt; types_traits&lt; Key, null_type, _Alloc, false &gt;::value_type, tree_node_metadata_dispatch&lt; Key, null_type, Cmp_Fn, Node_Update, _Alloc &gt;::type, _Alloc &gt;, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00217.html',1,'__gnu_pbds::detail']]],
  ['binary_5fcompose',['binary_compose',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00034.html',1,'__gnu_cxx']]],
  ['binary_5ffunction',['binary_function',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5fpredicate_3a_3afirst_5fargument_5ftype_2c_20_5fpredicate_3a_3asecond_5fargument_5ftype_2c_20bool_20_3e',['binary_function&lt; _Predicate::first_argument_type, _Predicate::second_argument_type, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5ft1_2c_20_5ft2_2c_20_5fres_20_3e',['binary_function&lt; _T1, _T2, _Res &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; _Tp, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20_5ftp_20_3e',['binary_function&lt; _Tp, _Tp, _Tp &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20_5ftp_2c_20_5ftp_2c_20bool_20_3e',['binary_function&lt; _Tp, _Tp, bool &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5farg_2c_20_5fret_20_3e',['binary_function&lt; const _Tp *, _Arg, _Ret &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00455.html',1,'std']]],
  ['binary_5fheap',['binary_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00219.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fconst_5fiterator_5f',['binary_heap_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00220.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5fpoint_5fconst_5fiterator_5f',['binary_heap_point_const_iterator_',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00221.html',1,'__gnu_pbds::detail']]],
  ['binary_5fheap_5ftag',['binary_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00192.html',1,'__gnu_pbds']]],
  ['binary_5fnegate',['binary_negate',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00637.html',1,'std']]],
  ['binder1st',['binder1st',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00638.html',1,'std']]],
  ['binder2nd',['binder2nd',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00639.html',1,'std']]],
  ['binomial_5fdistribution',['binomial_distribution',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00640.html',1,'std']]],
  ['binomial_5fheap',['binomial_heap',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00222.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5fbase',['binomial_heap_base',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00223.html',1,'__gnu_pbds::detail']]],
  ['binomial_5fheap_5ftag',['binomial_heap_tag',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00193.html',1,'__gnu_pbds']]],
  ['bitmap_5fallocator',['bitmap_allocator',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00035.html',1,'__gnu_cxx']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00476.html',1,'std::__debug']]],
  ['bitset',['bitset',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00535.html',1,'std::__profile']]],
  ['bool_5fset',['bool_set',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00934.html',1,'std::tr2']]],
  ['branch_5fpolicy',['branch_policy',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00224.html',1,'__gnu_pbds::detail']]],
  ['branch_5fpolicy_3c_20node_5fcitr_2c_20node_5fcitr_2c_20_5falloc_20_3e',['branch_policy&lt; Node_CItr, Node_CItr, _Alloc &gt;',['https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a00225.html',1,'__gnu_pbds::detail']]]
];
